CS-144: caller id privacy issues
2600hz/kazoo-stepswitch pull request #51
Opened 2024-04-04 22:04 UTC by kusalfernando

- Privacy settings are respected in on-net calls

2024-04-05 20:21 UTC, jamesaimonetti commented on src/stepswitch_local_extension.erl
> +            lager:info("built local extension: ~p", [Payload]),
I don't think we need to log this payload, right?

2024-04-05 20:24 UTC, kusalfernando commented on src/stepswitch_local_extension.erl
> +            lager:info("built local extension: ~p", [Payload]),
yeah, I will remove it.

2024-04-05 20:25 UTC, jamesaimonetti requested changes

2024-04-05 20:25 UTC, jamesaimonetti commented on src/stepswitch_util.erl
> -    fun({?KEY_OUTBOUND_CALLER_ID_NUMBER, N}) when N =:= Number -> 'false';
This function has existed for at least 8 years like this (probably more). Can you show me what you saw/tested that made this change necessary?

2024-04-05 20:32 UTC, kusalfernando commented on src/stepswitch_util.erl
> -    fun({?KEY_OUTBOUND_CALLER_ID_NUMBER, N}) when N =:= Number -> 'false';
That removed `{<<"Outbound-Caller-ID-Number">>,<<"+12095094615">>}, {<<"Outbound-Caller-ID-Name">>,<<"Account Admin">>}` from the endpoint payload. My guess was it's used to remove entries other than specified `Name` and `Number`.

2024-04-05 20:45 UTC, jamesaimonetti commented on src/stepswitch_util.erl
> -    fun({?KEY_OUTBOUND_CALLER_ID_NUMBER, N}) when N =:= Number -> 'false';
You can't guess here though; the code has been around a long time. You might have to do some more digging into why the code checks for equality.

To be clear, old code can change but we need to be certain why the old code no longer is valid.

2024-04-05 20:54 UTC, jamesaimonetti commented on src/stepswitch_util.erl
> -    fun({?KEY_OUTBOUND_CALLER_ID_NUMBER, N}) when N =:= Number -> 'false';
https://github.com/2600hz/kazoo/commit/62292f7f994c3081abd83d71d0511f5275e7fec8

2024-04-05 20:55 UTC, jamesaimonetti commented on src/stepswitch_util.erl
> -    fun({?KEY_OUTBOUND_CALLER_ID_NUMBER, N}) when N =:= Number -> 'false';
Which suggests that, if the top-level of the bridge string has the same caller ID settings, remove CID from the endpoint-specific settings.

2024-04-05 20:59 UTC, kusalfernando commented on src/stepswitch_util.erl
> -    fun({?KEY_OUTBOUND_CALLER_ID_NUMBER, N}) when N =:= Number -> 'false';
Got it. I will remove that change.

2024-04-08 21:47 UTC, lazedo requested changes
please explain the approach your taking mentioning any other commits in any other repos.

2024-04-08 21:47 UTC, lazedo commented on src/stepswitch_local_extension.erl
> +                 ,{<<"Privacy-Method">>, kz_privacy:get_method(OffnetReq)}
what is the effect of this ? maybe something missing on `ecallmgr` ?

2024-04-08 22:02 UTC, kusalfernando commented on src/stepswitch_local_extension.erl
> +                 ,{<<"Privacy-Method">>, kz_privacy:get_method(OffnetReq)}
When I compared the payload which is passed to the call control exchange of on-net and off-net calls privacy fields were missing in on-net calls and adding these privacy fields fixed the issue.

2024-04-09 07:56 UTC, lazedo requested changes

2024-04-09 07:56 UTC, lazedo commented on src/stepswitch_local_extension.erl
> +                 ,{<<"Privacy-Method">>, kz_privacy:get_method(OffnetReq)}
you need to do the same in stepswitch_outbund

2024-04-09 17:17 UTC, kusalfernando commented on src/stepswitch_local_extension.erl
> +                 ,{<<"Privacy-Method">>, kz_privacy:get_method(OffnetReq)}
The payload which is passed to `kapi_dialplan:publish_command/2` of on-net calls are built under `stepswitch_local_extension:build_local_extension/1`. Sorry, I don't understand the reason to do the same in `stepswitch_outbund`.

2024-04-09 17:55 UTC, lazedo commented on src/stepswitch_local_extension.erl
> +                 ,{<<"Privacy-Method">>, kz_privacy:get_method(OffnetReq)}
it doesn't matter if it is an `on-net` call, what it matters is if the call `stays local` without leaving the cluster (using  loopback on the media server). that is valid for bridging calls and originating calls.

2024-04-09 18:52 UTC, kusalfernando commented on src/stepswitch_local_extension.erl
> +                 ,{<<"Privacy-Method">>, kz_privacy:get_method(OffnetReq)}
Sure, I will make the change.

2024-04-09 22:06 UTC, lazedo requested changes
drop the unrelated changes to `src/stepswitch_util.erl`

2026-04-12 19:47 UTC, closed without merging